apiVersion: v1
kind: Service
metadata:
  name: elrraggregator-k8s-svc
spec:
  selector:
    app: elrraggregator-k8s
  type: NodePort
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
      nodePort: 30037