CREATE DATABASE [IF NOT EXISTS] service_db;

CREATE SCHEMA [IF NOT EXISTS] elrr;

-- Navigate to elrr schema 
SET search_path TO elrr;

-- Create elrr tables 
CREATE TABLE IF NOT EXISTS elrr.accreditation (
    accreditationid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inserteddate timestamp(6) NULL,
    lastmodified timestamp(6) NULL,
    updatedby varchar(255) NULL,
    organizationaccredits varchar(255) NULL
);


    
CREATE TABLE IF NOT EXISTS elrr.configuration (
	configurationid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	configurationname varchar(255) NOT NULL,
	configurationvalue varchar(255) NULL,
	frequency varchar(255) NULL,
	starttime varchar(255) NULL,
	primarycontact varchar(255) NULL,
	primaryemail varchar(254) NULL,
	primaryorgname varchar(100) NULL,
	primaryphone varchar(255) NULL,
	secondarycontact varchar(255) NULL,
	secondaryemail varchar(254) NULL,
	secondaryorgname varchar(100) NULL,
	secondaryphone varchar(255) NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL
);


CREATE TABLE IF NOT EXISTS elrr.competency (
	competencyid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	competencydefinitionidentifier varchar(100) NULL,
	competencydefinitionidentifierurl text NULL,
	competencytaxonomyid varchar(100) NULL,
	competencydefinitionvalidstartdate date NULL,
	competencydefinitionvalideenddate date NULL,
	competencydefinitionparentidentifier varchar(100) NULL,
	competencydefinitionparenturl text NULL,
	competencydescriptionparentcode varchar(100) NULL,
	competencydefinitioncode varchar(100) NULL,
	competencydefinitiontype varchar(100) NULL,
	competencydefinitiontypeurl text NULL,
	competencydefinitionstatement text NULL,
	competencyframeworktitle varchar(100) NOT NULL,
	competencyframeworkversion varchar(100) NULL,
	competencyframeworkidentifier varchar(100) NULL,
	competencyframeworkdescription text NULL,
	competencyframeworksubject varchar(100) NULL,
	competencyframeworkvalidstartdate date NULL,
	competencyframeworkvalidenddate date NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL
);

 

CREATE TABLE IF NOT EXISTS elrr.course (
	courseid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	coursetitle varchar(300) NOT NULL,
	coursesubjectmatter varchar(100) NULL,
	coursesubjectabbreviation varchar(20) NULL,
	courseidentifier varchar(150) NOT NULL,
	courselevel varchar(50) NULL,
	coursenumber varchar(50) NULL,
	courseinstructionmethod varchar(50) NULL,
	coursestartdate date NULL,
	courseenddate date NULL,
	courseenrollmentdate date NULL,
	courseacademicgrade varchar(50) NULL,
	courseprovidername varchar(100) NULL,
	departmentname varchar(100) NULL,
	coursegradescalecode varchar(50) NULL,
	coursemetadatarepository varchar(50) NULL,
	courselrsendpoint varchar(50) NULL,
	coursedescription text NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL
);



CREATE TABLE IF NOT EXISTS elrr.courseaccreditation (
    courseaccreditationid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inserteddate timestamp(6) NULL,
    lastmodified timestamp(6) NULL,
    updatedby varchar(255) NULL
);



CREATE TABLE IF NOT EXISTS elrr.elrrauditlog (
	elrrauditlogid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	payload jsonb NULL,
	syncid int8 NOT NULL,
	recordstatus varchar(10) NULL, 
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL
);

-- Be sure to change sequence name
ALTER SEQUENCE elrr.elrrauditlog_elrrauditlogid_seq RENAME TO elrrauditlog_seq;



CREATE TABLE IF NOT EXISTS elrr.employment (
	employmentid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employername varchar(100) NOT NULL,
	employerdepartment varchar(100) NULL,
	hiredate date NULL,
	employmentstartdate date NULL,
	employmentenddate date NULL,
	joblevel varchar(100) NULL,
	occupation varchar(100) NULL,
	employed bpchar(1) NULL,
	primarycareercategory varchar(50) NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL
);

    
    
CREATE TABLE IF NOT EXISTS elrr.person (
	personid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(250) NOT NULL,
	firstname varchar(50) NOT NULL,
	middlename varchar(50) NULL,
	lastname varchar(50) NOT NULL,
	nameprefix varchar(50) NULL,
	titleaffixcode varchar(50) NULL,
	namesuffix varchar(50) NULL,
	qualificationaffixcode varchar(50) NULL,
	maidenname varchar(50) NULL,
	preferredname varchar(50) NULL,
	humanresourceidentifier text NULL,
	personnelidentificationsystem text NULL,
	birthdate date NULL,
	sex bpchar(1) NULL,
	primarylanguage varchar(50) NULL,
	militaryveteranindicator bpchar(1) NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL,
	CONSTRAINT ref_person FOREIGN KEY (personid) REFERENCES elrr.person(personid)
);
     


CREATE TABLE IF NOT EXISTS elrr.contactinformation (
	contactinformationid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	personid int4 NOT NULL,
	contactinformation varchar(20) NOT NULL,
	telephonenumber varchar(20) NULL,
	isprimaryindicator bpchar(1) NULL,
	telephonetype varchar(20) NULL,
	electronicmailaddress varchar(254) NULL,
	electronicmailaddresstype varchar(20) NULL,
	emergencycontact varchar(250) NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL,
	CONSTRAINT refperson20 FOREIGN KEY (personid) REFERENCES elrr.person(personid)
);



-- Re-visit relationships
CREATE TABLE IF NOT EXISTS elrr.learnerprofile (
	learnerprofileid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	personid int8 NOT NULL,
	learneraddressid int8 NULL,
	contactinformationid int8 NULL,
	employmentid int8 NOT NULL,
	positionid int8 NULL,
	citizenshipid int8 NULL,
	studentid int8 NULL,
	courseid int8 NULL,
	courseaccreditationid int8 NULL,
	competencyid int8 NULL,
	credentialid int8 NULL,
	organizationid int8 NULL,
	organizationaddressid int8 NULL,
	accreditationid int8 NULL,
	activitystatus varchar(10) NOT NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL,
    CONSTRAINT refemployment25 FOREIGN KEY (employmentid) REFERENCES elrr.employment(employmentid)
);



CREATE TABLE IF NOT EXISTS elrr.organization (
	organizationid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizationname varchar(100) NOT NULL,
	organizationidentifier varchar(100) NULL,
	organizationidentificationcode varchar(100) NULL,
	organizationidentificationsystem varchar(100) NULL,
	industrytypeidentifier varchar(100) NULL,
	organizationfein varchar(100) NULL,
	organizationdescription text NULL,
	parentorganization varchar(100) NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate timestamp NULL,
	lastmodified timestamp NULL
);



CREATE TABLE IF NOT EXISTS elrr.role (
	roleid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rolename varchar(20) NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate date NULL,
	lastmodified date NULL
);



--Re-visit role/person relationships => view
CREATE TABLE IF NOT EXISTS elrr.rolerelations (
	rolerelationsid int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parentroleid int4 NOT NULL,
	parentpersonid int4 NOT NULL,
	childroleid int4 NOT NULL,
	childpersonid int4 NOT NULL,
	recordstatus varchar(10) NULL,
	updatedby varchar(20) NULL,
	inserteddate date NULL,
	lastmodified date NULL
);