-- Navigate to elrr schema
SET search_path = elrr;

-- Drop elrr sequences
DROP SEQUENCE elrr.accreditation_seq;
DROP SEQUENCE elrr.competency_seq;
DROP SEQUENCE elrr.contactinformation_seq;
DROP SEQUENCE elrr.course_seq;
DROP SEQUENCE elrr.courseaccreditation_seq;
DROP SEQUENCE elrr.elrrauditlog_seq;
DROP SEQUENCE elrr.employment_seq;
DROP SEQUENCE elrr.learnerprofile_seq;
DROP SEQUENCE elrr.organization_seq;
DROP SEQUENCE elrr.person_seq;

-- Drop elrr tables
DROP TABLE IF EXISTS ACCREDIDATION
DROP TABLE IF EXISTS ROLERELATIONS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS LEARNERPROFILE;
DROP TABLE IF EXISTS CONTACTINFORMATION;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS EMPLOYMENT;  
DROP TABLE IF EXISTS ELRRAUDITLOG; 
DROP TABLE IF EXISTS COURSE; 
DROP TABLE IF EXISTS COMPETENCY;
DROP TABLE IF EXISTS CONFIGURATION; 