-- Navigate to elrr schema
SET search_path = elrr;

-- Drop elrr tables
DROP TABLE IF EXISTS elrr.ACCREDIDATION cascade
DROP TABLE IF EXISTS elrr.ROLERELATIONS cascade;
DROP TABLE IF EXISTS elrr.ROLE cascade;
DROP TABLE IF EXISTS elrr.ORGANIZATION cascade;
DROP TABLE IF EXISTS elrr.LEARNERPROFILE cascade;
DROP TABLE IF EXISTS elrr.CONTACTINFORMATION cascade;
DROP TABLE IF EXISTS elrr.PERSON cascade;
DROP TABLE IF EXISTS elrr.EMPLOYMENT cascade;  
DROP TABLE IF EXISTS elrr.ELRRAUDITLOG cascade; 
DROP TABLE IF EXISTS elrr.COURSE cascade; 
DROP TABLE IF EXISTS elrr.COMPETENCY cascade;
DROP TABLE IF EXISTS elrr.CONFIGURATION cascade; 